/* Editorial reframing of documented contributions. No inferred business metrics. */
window.caseNarratives = {
privatikaL: {
 color:'#cbdbaa',category:'Web · Frontend',cover:'images/24.jpg',
 es:{title:'Privatika',subtitle:'Hacer clara la primera impresión.',challenge:'Presentar una aplicación de gestión de términos y condiciones desde una web rápida, clara y preparada para ser encontrada.',approach:'Abordé la landing desde tres frentes: componentes reutilizables para mantener coherencia, optimización de SEO y Core Web Vitals, y animaciones para acompañar la navegación. Conecté el envío de correos mediante una API REST.',solution:'Una landing desarrollada con Vite y Tailwind CSS, con componentes reutilizables, animaciones e integración de correo.',focus:'Claridad, rendimiento y una experiencia coherente desde el primer contacto.'},
 en:{title:'Privatika',subtitle:'Making the first impression clear.',challenge:'Introduce a terms and conditions management app through a fast, clear website built to be discoverable.',approach:'I approached the landing page through three areas: reusable components for consistency, SEO and Core Web Vitals optimization, and motion to support navigation. I connected email delivery through a REST API.',solution:'A Vite and Tailwind CSS landing page with reusable components, animation and email integration.',focus:'Clarity, performance and a consistent experience from the first interaction.'}},
privatika: {
 color:'#b4c4df',category:'Web · Frontend',cover:'images/30.jpg',
 es:{title:'Privatika App',subtitle:'Ordenar la complejidad de la gestión.',challenge:'Reunir usuarios, términos y condiciones, permisos y claves de conexión dentro de un panel administrativo.',approach:'Mi trabajo se centró en el frontend: estructuré el dashboard, gestioné estados globales y conecté las operaciones con la API REST. La gestión de roles y permisos formó parte de esa experiencia.',solution:'Un dashboard que integra creación de usuarios, gestión de términos y condiciones y generación de claves para conectar aplicaciones o sitios web.',focus:'Dar una estructura común a operaciones relacionadas.'},
 en:{title:'Privatika App',subtitle:'Bringing structure to complex management.',challenge:'Bring users, terms and conditions, permissions and connection keys into an administrative dashboard.',approach:'My work focused on the frontend: I structured the dashboard, managed global state and connected operations to the REST API. Roles and permissions were part of that experience.',solution:'A dashboard integrating user creation, terms and conditions management and key generation for connected apps or websites.',focus:'Giving related operations a shared structure.'}},
skyfleeter: {
 color:'#c8c1ad',category:'Web / Mobile · Full stack',cover:null,
 es:{title:'Skyfleeter',subtitle:'Conectar la operación de una flota.',challenge:'Atender necesidades de soporte, inspecciones, mantenimiento, documentación y seguimiento de viajes dentro de una solución de flotas.',approach:'Abordé tareas concretas de la operación: tickets para soporte, códigos QR y PDFs para inspecciones, correos para mantenimiento y documentación de conductores. También trabajé en la app móvil de seguimiento de viajes, geolocalización y rutas.',solution:'Funciones web y móviles para apoyar la gestión operativa de flotas, sobre una base de .NET, C# y SQL.',focus:'Conectar la información de vehículos, conductores y viajes.'},
 en:{title:'Skyfleeter',subtitle:'Connecting fleet operations.',challenge:'Address support, inspection, maintenance, documentation and trip tracking needs within a fleet solution.',approach:'I worked on specific operational tasks: support tickets, QR codes and PDFs for inspections, maintenance emails and driver documentation. I also worked on the mobile app for trip tracking, geolocation and routes.',solution:'Web and mobile features supporting fleet operations, on a .NET, C# and SQL foundation.',focus:'Connecting information about vehicles, drivers and trips.'}},
muravi: {
 color:'#d7b9a7',category:'Android · Retail',cover:'images/20.jpg',
 es:{title:'Muravi',subtitle:'Del inventario a la decisión.',challenge:'Gestionar prendas por talla, color y temporada, relacionando las existencias con las ventas y los reportes de rentabilidad.',approach:'Estructuré la aplicación con MVVM y Firebase para conectar el control de stock con el registro de ventas. Incorporé seguridad biométrica y pruebas automatizadas en componentes críticos.',solution:'Una aplicación Android con seguimiento de inventario en tiempo real, gestión de prendas y ventas, y reportes automáticos de rentabilidad.',focus:'Mantener conectados inventario, ventas y reportes.'},
 en:{title:'Muravi',subtitle:'From inventory to decisions.',challenge:'Manage clothing by size, color and season, connecting stock with sales and profitability reports.',approach:'I structured the application using MVVM and Firebase to connect stock control with sales recording. I added biometric security and automated testing of critical components.',solution:'An Android app with real-time inventory tracking, clothing and sales management, and automated profitability reports.',focus:'Keeping inventory, sales and reporting connected.'}},
salon: {
 color:'#d9bdd2',category:'Android · Servicios',cover:'images/4.jpeg',
 es:{title:'App Salon',subtitle:'Dar estructura a cada reserva.',challenge:'Gestionar los servicios y las citas de un salón de belleza desde una aplicación móvil.',approach:'Organicé la aplicación con arquitectura MVVM y conecté la gestión de citas con Firebase. El flujo reúne las operaciones de creación y control de reservas, con notificaciones push.',solution:'Una aplicación Android nativa en Java con reservas en tiempo real y gestión de citas.',focus:'Reunir servicios y reservas en una experiencia móvil.'},
 en:{title:'Salon App',subtitle:'Giving every booking structure.',challenge:'Manage beauty salon services and appointments through a mobile application.',approach:'I organized the app with MVVM architecture and connected appointment management to Firebase. The flow brings booking creation and management together, with push notifications.',solution:'A native Android app in Java with real-time bookings and appointment management.',focus:'Bringing services and bookings into a mobile experience.'}},
dentist: {
 color:'#b9d5cd',category:'Android · Salud',cover:'images/11.jpeg',
 es:{title:'App Dentista',subtitle:'Acompañar más allá de la cita.',challenge:'Gestionar citas de un consultorio dental y acompañarlas con recordatorios y consejos de higiene bucal.',approach:'Conecté la gestión de citas con Firebase sobre una arquitectura MVVM. Incorporé notificaciones push para recordatorios y consejos, junto con pruebas automatizadas de componentes críticos.',solution:'Una aplicación Android que reúne citas, notificaciones y contenido de higiene bucal.',focus:'Conectar la gestión de citas con los recordatorios.'},
 en:{title:'Dentist App',subtitle:'Supporting care beyond appointments.',challenge:'Manage dental appointments alongside reminders and oral hygiene guidance.',approach:'I connected appointment management to Firebase using MVVM architecture. I integrated push notifications for reminders and guidance, alongside automated testing of critical components.',solution:'An Android app bringing appointments, notifications and oral hygiene content together.',focus:'Connecting appointment management with reminders.'}}
};
